# Generated by Django 5.2.2 on 2025-07-03 13:11

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddField(
            model_name="booking",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[(models.F("room"), "="), ("date_range", "&&")],
                name="prevent_overlapping_bookings",
            ),
        ),
    ]
